import os
import logging
from typing import Dict, Any, List, Optional
from pydantic import ValidationError

from app.brain.llm_service import ask_llm
from app.pipeline.optimization_service import retrieve_and_rerank, compress_context

# 🆕 Import your agent loop (Adjust the path if your agent_core.py is located elsewhere)
from app.brain.llm_service import run_agent_loop 

logger = logging.getLogger(__name__)

# ==========================================================
# 🚀 MAIN PIPELINE: ask_rfq
# ==========================================================
async def ask_rfq(question: str, top_k: int = 8, max_context_tokens: int = 4000) -> Dict[str, Any]:
    """
    Orchestrates the full RFQ query pipeline: 
    Intent Routing -> Hybrid Retrieval -> Reranking -> Compression -> LLM Generation.
    """
    logger.info(f"RFQ Query received: '{question}'")

    try:
        # 🆕 1. AUTO-ROUTER: Detect Comparison/Complex Intent
        compare_keywords = ["compare", "difference", "vs", "versus", "discrepancy", "discrepancies"]
        if any(keyword in question.lower() for keyword in compare_keywords):
            logger.info("🔀 Comparison intent detected! Routing directly to Agent...")
            agent_answer = await run_agent_loop(question)
            return _build_response(
                question=question, 
                answer=agent_answer or "No answer generated by agent.", 
                sources=["Agent Multi-Step Analysis"], 
                confidence=0.95
            )

        # 2. Hybrid Retrieval + Reranking (Standard Fast-Path)
        results, confidence_score = await retrieve_and_rerank(
            query=question, 
            initial_k=20, 
            final_k=top_k 
        )

        if not results:
            return _build_response(question, "No relevant information found in the documents.", confidence=0.0)

        # 3. Metadata Extraction
        unique_sources = {
            os.path.basename(str(r.get("metadata", {}).get("source", "")))
            for r in results if r.get("metadata", {}).get("source")
        }
        sources = list(unique_sources)

        # 4. Smart Context Compression
        context = compress_context(results, max_tokens=max_context_tokens)
        chunks_used = len(results)

        # 5. Context Guard (Safety check)
        if len(context.strip()) < 20: 
            return _build_response(
                question=question, 
                answer="I found some data, but it's not enough to form a complete, accurate answer.", 
                sources=sources, 
                chunks_used=chunks_used, 
                confidence=confidence_score, 
                context=context
            )

        # 6. Generation
        answer = await ask_llm(question, context)
        return _build_response(question, answer, sources, chunks_used, confidence_score, context)

    except Exception as e:
        logger.exception(f"❌ Query processing failed: {str(e)}")
        return _build_response(question, "I encountered an error while analyzing the documents.", error=str(e))

# ==========================================================
# 🛠️ AGENT TOOL: search_documents
# ==========================================================
async def search_documents(query: str) -> str:
    """Tool: Agent search with deep retrieval."""
    logger.info(f"🛠️ Tool: search_documents | Query: '{query}'")
    
    try:
        # Fetch 40 chunks initially to allow the reranker to find subtle details
        results, _ = await retrieve_and_rerank(query=query, initial_k=40, final_k=10)
        
        if not results:
            return "No relevant data found for this specific query."
                
        # Include metadata in the tool output so the Agent knows which file is which
        context_blocks = []
        for r in results:
            src = os.path.basename(str(r.get("metadata", {}).get("source", "Unknown")))
            text = r.get("text", "[No text content]")
            context_blocks.append(f"[{src}]: {text}")
            
        return "\n\n".join(context_blocks)
        
    except Exception as e:
        logger.exception(f"❌ Tool execution failed: {str(e)}")
        return f"Error executing search tool: {str(e)}"

# ==========================================================
# 🏗️ HELPER: Standardized Response Builder
# ==========================================================
def _build_response(
    question: str, 
    answer: str, 
    sources: Optional[List[str]] = None, 
    chunks_used: int = 0, 
    confidence: float = 0.0, 
    context: str = "",
    error: Optional[str] = None
) -> Dict[str, Any]:
    """Ensures consistent JSON output across all pipeline stages."""
    
    context_preview = context[:500] + ("..." if len(context) > 500 else "")
    
    response = {
        "question": question,
        "answer": answer,
        "sources": sources or [],
        "chunks_used": chunks_used,
        "confidence": confidence,
        "context_preview": context_preview
    }
    if error:
        response["error"] = error
    return response